version: 2
jobs:
  build:
    docker:
    - image: docker:19-git

    working_directory: ~/workdir

    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
        - v1-{{ .Branch }}
        paths:
        - /caches/layercache.tar
    - run:
        name: Install bash and curl
        command: |
          set +o pipefail
          apk --no-cache update  && apk --no-cache add bash curl && apk upgrade libcurl
    - run:
        name: Load Docker image layer cache
        command: |
          mkdir -p /caches
          set +o pipefail
          docker load -i /caches/layercache.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWD

          export DOCKER_REPO_NAME=gulli/cicdw-myip-api
          export PUSHARG=
          pwd
          ls -lart
          (./build-docker.sh ${PUSHARG})

    - deploy:
        name: conditionally run a deploy job
        command: |
          # replace this with your build/deploy check (i.e. current branch is "release")
          env
          if [[ true ]]; then
            curl --user ${CIRCLE_API_USER_TOKEN}: \
              --data build_parameters[CIRCLE_JOB]=deploy_docker \
              --data revision=$CIRCLE_SHA1 \
              https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
          fi

    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
        - /caches/layercache.tar
